package net.xvidia.vowmee.network;


public interface IAPIConstants {
	int API_KEY_AUTH_FACEBOOK = 1;
	int API_KEY_AUTH_TWITTER = 2;
	int API_KEY_SOCIAL_REGISTER = 3;
	int API_KEY_LAYOUT_TIME_OFFLINE = 4;
	int API_KEY_ONOFF_BOX = 5;
	int API_KEY_ONOFF_APP = 6;
	int API_KEY_ONOFF_SCREEN = 7;
	int API_KEY_ONOFF_BOX_OFFLINE = 8;
	int API_KEY_ONOFF_APP_OFFLINE = 9;
	int API_KEY_ONOFF_SCREEN_OFFLINE = 10;
	int API_KEY_BOX_LOCATION = 11;
	int API_KEY_BOX_INVENTORY_DATA = 12;
	int API_KEY_BOX_GET_INVENTORY_DATA = 13;
	int API_KEY_BOX_DOWNLOADING_STATUS = 14;
	int API_KEY_BOX_UPDATE_APK = 15;

}
